### ISSUE TITLE
Button groups do not work for mobile

### ISSUE THREAD

**Issue by feeds** [match4everyone/match4healthcare#174]

**Comment by maltezacharias** [comment]
Is this still the case? Have you tried replacing label with button in the html? Maybe that would already fix it?

**Comment by maltezacharias** [comment]
https://app.slack.com/client/T0100P155FD/C010K4T5YGZ/thread/C010K4T5YGZ-1585296366.041300

Das Problem ist, dass man nicht zur Seite scrollen kann:
![image](https://user-images.githubusercontent.com/9914287/78085807-4c566e00-73bc-11ea-872a-3cde9c4ae086.png)

@andyz02 kannst du da was machen?
