### ISSUE TITLE
Manually change language

### ISSUE THREAD

**Issue by feeds** [match4everyone/match4healthcare#186]

**Comment by maltezacharias** [comment]
also please check, why do so many people get the english page instead of the german. Maybe locale de_AT also goes to english?

**Comment by maltezacharias** [comment]
https://match4healthcare.slack.com/archives/C010K4T5YGZ/p1585251845008400?thread_ts=1585251464.005200&cid=C010K4T5YGZ

**Comment by maltezacharias** [comment]
@andyz02 design Vorschlag bitte

**Comment by Baschdl** [comment]
I would use [https://docs.djangoproject.com/en/2.0/topics/i18n/translation/#url-internationalization](https://docs.djangoproject.com/en/2.0/topics/i18n/translation/#url-internationalization). The buttons `en` and `de` would just redirect to the language sites which is like storing the setting.

**Comment by maltezacharias** [comment]
Ist erledigt
