### ISSUE TITLE
Große Textblöcke kleiner machen und ins Englische übersetzen

### ISSUE THREAD

**Issue by andreaskind** [match4everyone/match4healthcare#194]

**Comment by maltezacharias** [comment]
Gemeint: Wir haben im Moment auf den großen HTML Seiten **einen** Blocktrans der ewig lang und voller HTML ist. 
Sollten wir mindestens auf Absätze runterbrechen. Geringes HTML wie <b>, <a> usw. ist ok, aber die riesigen Blöcke zu übersetzen macht a) keinen Spaß und wird b) super aufwenidg, weil es dann bei jeder kleinen Änderung sehr schwierig ist zu wissen, was sich in der Übersetzung geändert hat

**Comment by maltezacharias** [comment]
Too broad an issue. 
Closing. I redid all translations today and it seems it's alright for now.
