### ISSUE TITLE
New text with grammar fixes for "Hospital Signup"

### ISSUE THREAD

**Issue by andreaskind** [match4everyone/match4healthcare#258]
für diese Seite: https://match4healthcare.de/accounts/signup_hospital

Hier der neue Text:

<p>Bitte geben Sie hier die allgemeinen Angaben zu Ihrer Institution an. Nach dem Klicken auf “Registrieren” erhalten Sie eine E-Mail mit einem Bestätigungslink. Über diesen Link können Sie ein Passwort für Ihren Account bei uns setzen und sich einloggen. Bei match4healthcare können Sie eine Suchanfrage mit den von Ihnen gewünschten Kriterien (Ausbildungsstand etc.) an Helfende erstellen. Nachdem Sie die gewünschten Personen ausgesucht haben, können Sie eine Mail verfassen und über unsere Plattform an die Helfenden verschicken. Hierbei geben wir bewusst, aus Datenschutzgründen, die Namen der Helfenden nicht an. </p>
<br>
<p> Der E-Mail Versand erfolgt dann nach einer Validierung Ihrer Institution automatisch durch uns. Die Validierung Ihrer Institution verläuft automatisch über unser Team und sollte innerhalb von 1-2 Tagen geschehen. Falls Sie Hilfe benötigen, erreichen Sie uns unter info@match4healthcare.de. </p>

**Comment by josauder** [comment]
@andreaskind Please directly also provide an english translation

**Comment by Baschdl** [comment]
@andreaskind Used deepl, please check and feel free to edit if you want something changed
