### ISSUE TITLE
new text for "Suchanfragen" site, übersetzt

### ISSUE THREAD

**Issue by andreaskind** [match4everyone/match4healthcare#262]
Neuer, korrigierter und gegendeter Text für: 
https://www.match4healthcare.de/ineedstudent/students/DE/10559/0

<h1>Suchanfrage erstellen</h1>
<h2>Hier können Sie bereits registrierte Helfende durchsuchen und kontaktieren.</h2>
<br>
<p>(in fett) Sie suchen zum Beispiel nach examinierten Pflegekräften? </p>

<br>

Dann wählen Sie unter "Ausbildungen" aus, dass ein*e Helfende*r eine Pflegeausbildung haben muss, indem Sie auf das Feld "muss" klicken. In dem geöffneten Ausbildungsfeld weiter unten können Sie nun auswählen, dass die Pflegekraft schon berufstätig sein muss. Falls eine Ausbildung nicht relevant für Ihre Auswahl sein sollte, so müssen Sie nichts weiter auswählen.

<br>

Ihre Institution kann außerdem eine Unterkunft oder eine Vergütung für Helfende anbieten? Super! Um uns dies mitzuteilen, hacken Sie bitte die entsprechende Checkbox weiter unten an. Nun einfach auf den "Filter aktualisieren" klicken und Sie können die passenden Kandidaten in der Tabelle ansehen und ihnen eine E-Mail senden. 

<h1>Setting up a search</h1>
<h2>Search and contact volunteers</h2>
<br>
<p>(in fett) Are you looking for caregivers? </p>

<br>
Please select which training a volunteer e.g. caregiver needs to have by clicking the "must" button. Further below you may then choose the required level of training. If the level of training is not of interest for your selection, you won't have to choose anything.

<br>
Your institution is also capable of providing accommodation or payment? That's great! Please tick the referring Checkbox further below. Now just hit the "Update Filter" button and the matching candidates will show up in the list down below. You may then select those people you want to send a message to.

**Comment by josauder** [comment]
@andreaskind please provide an english translation
