### ISSUE TITLE
Render mapview asynchronously 

### ISSUE THREAD

**Issue by Baschdl** [match4everyone/match4healthcare#47]
Map is currently only rendered after receiving the data from the DB

**Comment by Baschdl** [comment]
Could be done for launch but no priority

**Comment by maltezacharias** [comment]
Lösungsidee: 
JSON-Endpoint in Python, der per XMLHttpRequest aus der MapView aufgerufen wird und dann die Marker auf der Karte erstellt, sobald die Daten geladen wurden

cave: Endpoint auf jeden Fall cachen, die Liste der Helfer sollte nicht ständig neu generiert werden müssen, so wie wir esauf den MapView Seiten schon umgesetzt haben.

JSON-Endpoint müsste liefern:
```
{
  markers: [
    {
      lat: 53.654419827214696, 
      lon: 10.3612254451413, 
      city: "Lütjensee", 
      count: 1, 
      country: 'DE', 
      zip: '22952' 
    },
    ...
  ]
}
```
