### ISSUE TITLE
Check with Django checklist

### ISSUE THREAD

**Issue by Baschdl** [match4everyone/match4healthcare#78]
Check [https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/](https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/)

**Comment by Baschdl** [comment]
`docker exec backend python3 manage.py check --deploy` gives the following hints:

WARNINGS:
?: (security.W004) You have not set a value for the SECURE_HSTS_SECONDS setting. If your entire site is served only over SSL, you may want to consider setting a value and enabling HTTP Strict Transport Security. Be sure to read the documentation first; enabling HSTS carelessly can cause serious, irreversible problems.
?: (security.W008) Your SECURE_SSL_REDIRECT setting is not set to True. Unless your site should be available over both SSL and non-SSL connections, you may want to either set this setting True or configure a load balancer or reverse-proxy server to redirect all connections to HTTPS.
?: (security.W012) SESSION_COOKIE_SECURE is not set to True. Using a secure-only session cookie makes it more difficult for network traffic sniffers to hijack user sessions.
?: (security.W016) You have 'django.middleware.csrf.CsrfViewMiddleware' in your MIDDLEWARE, but you have not set CSRF_COOKIE_SECURE to True. Using a secure-only CSRF cookie makes it more difficult for network traffic sniffers to steal the CSRF token.
?: (security.W022) You have not set the SECURE_REFERRER_POLICY setting. Without this, your site will not send a Referrer-Policy header. You should consider enabling this header to protect user privacy.

Go through checklist again.

**Comment by maltezacharias** [comment]
Meine Meinung:
- HSTS: Starkes Nein. Ist zu risikobehaftet
- SECURE_SSL_REDIRECT: Im Reverse-Proxy erledigt
- SESSION_COOKIE_SECURE, CSRF_COOKIE_SECURE: bitte setzen, müssen wir aber prüfen ob das mit dem reverse proxy geht. Ich denke ja.
- SECURE_REFERRER_POLICY: same-origin bitte setzen.

**Comment by maltezacharias** [comment]
Ich korrigier mich: HSTS auf jeden Fall, wäre aber am Nginx zu setzen glaub ich
